# Call this whatever you want
name: scrape

# When does it get run?
on:
  # workflow_dispatch means "I can click a button and force it to run"
  workflow_dispatch:
  # schedule/cron means "on a set schedule"
  schedule:
    - cron: '*/30 * * * *'
jobs:
  scrape:
    # For some reason, we run love versions of linux
    runs-on: ubuntu-latest
    steps:
      # Download all of the code from your repo
      - name: Check out this repo
        uses: actions/checkout@v2
      # Set up Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      #
      - name: Install necessary Python packages
        run: pip install pandas beautifulsoup4 requests datetime
        
      # MAKE SURE YOUR SCRAPER FILENAME MATCHES THE FILENAME HERE!!
      - name: Run world_temperature script
        run: python hot_index.py
        
      - name: Add and commit	
        run: |
          git add .	
          git config user.name "Automated"	
          git config user.email "actions@users.noreply.github.com"	
          git commit --allow-empty -m "Latest data"	
      - name: Push	
        run: git push
